apiVersion: apps/v1
kind: Deployment
metadata:
  name: wx-chat-rebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wx-chat-rebot
  template:
    metadata:
      labels:
        app: wx-chat-rebot
    spec:
      containers:
        - name: wx_chat_rebot
          image: $image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: wx-chat-rebot
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: wx-chat-rebot
  selector:
    app: wx-chat-rebot